#!/bin/bash
# Author: Minhazul Haq Shawon <minhazul.haq@gmail.com> 2012
# Always thanks to: Aniruddha Adhikary <aniruddha@adhikary.net>

# NOTE Change this to your ISP rearm string
PROVIDER="banglalion.com.bd"

MAC=$(wimaxc versions | grep MAC | cut -d' ' -f3)

# NOTE this might be required to manupulate identity format
#MAC=$(wimaxc versions | grep MAC | cut -d' ' -f3) # | sed s/-/:/g)

if [ $MAC  ]
then
	if [ $# != 2 ]
	then
		echo "Please input correct args: <uid> <passwd>"
		exit 1
	fi
else
	echo "No device. Exiting..."
	 exit 1
fi

wimaxc set UserIdentity $1
wimaxc set UserPassword $2
wimaxc set TTLSAnonymousIdentity $MAC@$PROVIDER
wimaxc options save